language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 8

before_install:
  - npm install -g npm
  - npm install coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
