language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: storybook-static
  on:
    branch: master
