language: node_js

node_js:
  - '10'

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn build-storybook

deploy:
  # deploy to npm
  - provider: script
    skip_cleanup: true
    script:
      - NPM_TOKEN=$NPM_TOKEN GH_TOKEN=$GH_TOKEN yarn semantic-release
    on:
      branch: master
  # deploy to github pages
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: storybook-static
    on:
      branch: master
