language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
before_install:
  - npm install codecov.io coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run deploy-gh
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
